require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/conciliation_concepts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ConciliationConcept. As you add validations to ConciliationConcept, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ConciliationConcept.create! valid_attributes
      get conciliation_concepts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      conciliation_concept = ConciliationConcept.create! valid_attributes
      get conciliation_concept_url(conciliation_concept)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_conciliation_concept_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      conciliation_concept = ConciliationConcept.create! valid_attributes
      get edit_conciliation_concept_url(conciliation_concept)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ConciliationConcept" do
        expect {
          post conciliation_concepts_url, params: { conciliation_concept: valid_attributes }
        }.to change(ConciliationConcept, :count).by(1)
      end

      it "redirects to the created conciliation_concept" do
        post conciliation_concepts_url, params: { conciliation_concept: valid_attributes }
        expect(response).to redirect_to(conciliation_concept_url(ConciliationConcept.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ConciliationConcept" do
        expect {
          post conciliation_concepts_url, params: { conciliation_concept: invalid_attributes }
        }.to change(ConciliationConcept, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post conciliation_concepts_url, params: { conciliation_concept: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested conciliation_concept" do
        conciliation_concept = ConciliationConcept.create! valid_attributes
        patch conciliation_concept_url(conciliation_concept), params: { conciliation_concept: new_attributes }
        conciliation_concept.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the conciliation_concept" do
        conciliation_concept = ConciliationConcept.create! valid_attributes
        patch conciliation_concept_url(conciliation_concept), params: { conciliation_concept: new_attributes }
        conciliation_concept.reload
        expect(response).to redirect_to(conciliation_concept_url(conciliation_concept))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        conciliation_concept = ConciliationConcept.create! valid_attributes
        patch conciliation_concept_url(conciliation_concept), params: { conciliation_concept: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested conciliation_concept" do
      conciliation_concept = ConciliationConcept.create! valid_attributes
      expect {
        delete conciliation_concept_url(conciliation_concept)
      }.to change(ConciliationConcept, :count).by(-1)
    end

    it "redirects to the conciliation_concepts list" do
      conciliation_concept = ConciliationConcept.create! valid_attributes
      delete conciliation_concept_url(conciliation_concept)
      expect(response).to redirect_to(conciliation_concepts_url)
    end
  end
end
