require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/credit_bureaus", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CreditBureau. As you add validations to CreditBureau, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CreditBureau.create! valid_attributes
      get credit_bureaus_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      credit_bureau = CreditBureau.create! valid_attributes
      get credit_bureau_url(credit_bureau)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_credit_bureau_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      credit_bureau = CreditBureau.create! valid_attributes
      get edit_credit_bureau_url(credit_bureau)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CreditBureau" do
        expect {
          post credit_bureaus_url, params: { credit_bureau: valid_attributes }
        }.to change(CreditBureau, :count).by(1)
      end

      it "redirects to the created credit_bureau" do
        post credit_bureaus_url, params: { credit_bureau: valid_attributes }
        expect(response).to redirect_to(credit_bureau_url(CreditBureau.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CreditBureau" do
        expect {
          post credit_bureaus_url, params: { credit_bureau: invalid_attributes }
        }.to change(CreditBureau, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post credit_bureaus_url, params: { credit_bureau: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested credit_bureau" do
        credit_bureau = CreditBureau.create! valid_attributes
        patch credit_bureau_url(credit_bureau), params: { credit_bureau: new_attributes }
        credit_bureau.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the credit_bureau" do
        credit_bureau = CreditBureau.create! valid_attributes
        patch credit_bureau_url(credit_bureau), params: { credit_bureau: new_attributes }
        credit_bureau.reload
        expect(response).to redirect_to(credit_bureau_url(credit_bureau))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        credit_bureau = CreditBureau.create! valid_attributes
        patch credit_bureau_url(credit_bureau), params: { credit_bureau: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested credit_bureau" do
      credit_bureau = CreditBureau.create! valid_attributes
      expect {
        delete credit_bureau_url(credit_bureau)
      }.to change(CreditBureau, :count).by(-1)
    end

    it "redirects to the credit_bureaus list" do
      credit_bureau = CreditBureau.create! valid_attributes
      delete credit_bureau_url(credit_bureau)
      expect(response).to redirect_to(credit_bureaus_url)
    end
  end
end
