require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/f_reasons_concepts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FReasonsConcept. As you add validations to FReasonsConcept, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FReasonsConcept.create! valid_attributes
      get f_reasons_concepts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      f_reasons_concept = FReasonsConcept.create! valid_attributes
      get f_reasons_concept_url(f_reasons_concept)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_f_reasons_concept_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      f_reasons_concept = FReasonsConcept.create! valid_attributes
      get edit_f_reasons_concept_url(f_reasons_concept)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FReasonsConcept" do
        expect {
          post f_reasons_concepts_url, params: { f_reasons_concept: valid_attributes }
        }.to change(FReasonsConcept, :count).by(1)
      end

      it "redirects to the created f_reasons_concept" do
        post f_reasons_concepts_url, params: { f_reasons_concept: valid_attributes }
        expect(response).to redirect_to(f_reasons_concept_url(FReasonsConcept.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FReasonsConcept" do
        expect {
          post f_reasons_concepts_url, params: { f_reasons_concept: invalid_attributes }
        }.to change(FReasonsConcept, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post f_reasons_concepts_url, params: { f_reasons_concept: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested f_reasons_concept" do
        f_reasons_concept = FReasonsConcept.create! valid_attributes
        patch f_reasons_concept_url(f_reasons_concept), params: { f_reasons_concept: new_attributes }
        f_reasons_concept.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the f_reasons_concept" do
        f_reasons_concept = FReasonsConcept.create! valid_attributes
        patch f_reasons_concept_url(f_reasons_concept), params: { f_reasons_concept: new_attributes }
        f_reasons_concept.reload
        expect(response).to redirect_to(f_reasons_concept_url(f_reasons_concept))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        f_reasons_concept = FReasonsConcept.create! valid_attributes
        patch f_reasons_concept_url(f_reasons_concept), params: { f_reasons_concept: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested f_reasons_concept" do
      f_reasons_concept = FReasonsConcept.create! valid_attributes
      expect {
        delete f_reasons_concept_url(f_reasons_concept)
      }.to change(FReasonsConcept, :count).by(-1)
    end

    it "redirects to the f_reasons_concepts list" do
      f_reasons_concept = FReasonsConcept.create! valid_attributes
      delete f_reasons_concept_url(f_reasons_concept)
      expect(response).to redirect_to(f_reasons_concepts_url)
    end
  end
end
