XDB_HOST: localhost
DB_HOST: localhost
DB_DATABASE: credits_factor_global
DB_USERNAME: ''
DB_PASSWORD: ''
URL_BUREAU_PRODUCTION: 'https://app.moffin.mx/'
URL_BUREAU_DEVELOP: 'https://sandbox.moffin.mx/'
DOWNLOAD_FILES: 'https://analisisbucket.s3.amazonaws.com/credits_valuation'
TOKEN_BURO_PRODUCTION: 'Token: 59f899b9f9de3db1191b36d06cff5d63c563feba86a1678031637c9827156c7e'
TOKEN_BURO_DEVELOP: 'Token: 8d3f4980e76f1cf12da3005bac068636c1f36aa4cda8176de91bc64c00346f5b'
API_KEY_SAT_DEVELOP: '690cac03af62759362bd1fed20710ab4'
API_KEY_SAT_PRODUCTION: 'dc087a1fc8bb716cb2c2ff199c6d69c0'
URL_SAT_DEVELOP: 'https://api.sandbox.satws.com/'
URL_SAT_PRODUCTION: 'https://api.sandbox.satws.com/'
